"""Initial

Revision ID: 1814f69a2ba0
Revises: 
Create Date: 2024-03-12 17:37:07.267525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1814f69a2ba0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SEQUENCE id_seq")
    op.create_table('user_queries',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('id_seq'::regclass)"), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('product_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_queries_id'), 'user_queries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_queries_id'), table_name='user_queries')
    op.drop_table('user_queries')
    # ### end Alembic commands ###
